### ISSUE TITLE
Using IntentServer for Toast yields "Handler on a dead thread" error

### ISSUE THREAD

**Issue by shirriff** [googlesamples/android-Geofencing#1]
This code sample gives me errors:

02-05 12:16:01.464 W/MessageQueue( 5372): Handler (android.os.Handler) {128af18d} sending message to a Handler on a dead thread
02-05 12:16:01.464 W/MessageQueue( 5372): java.lang.IllegalStateException: Handler (android.os.Handler) {128af18d} sending message to a Handler on a dead thread
02-05 12:16:01.464 W/MessageQueue( 5372):   at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
02-05 12:16:01.464 W/MessageQueue( 5372):   at android.os.Handler.enqueueMessage(Handler.java:631)
02-05 12:16:01.464 W/MessageQueue( 5372):   at android.os.Handler.sendMessageAtTime(Handler.java:600)
02-05 12:16:01.464 W/MessageQueue( 5372):   at android.os.Handler.sendMessageDelayed(Handler.java:570)
02-05 12:16:01.464 W/MessageQueue( 5372):   at android.os.Handler.post(Handler.java:326)
02-05 12:16:01.464 W/MessageQueue( 5372):   at android.widget.Toast$TN.hide(Toast.java:379)
02-05 12:16:01.464 W/MessageQueue( 5372):   at android.app.ITransientNotification$Stub.onTransact(ITransientNotification.java:55)
02-05 12:16:01.464 W/MessageQueue( 5372):   at android.os.Binder.execTransact(Binder.java:446)

I believe the problem is GeofenceTransitionsIntentService displays a Toast, but the IntentService thread is short-lived, just for the lifetime of handling the Intent. There's some discussion at http://stackoverflow.com/questions/4443278/toast-sending-message-to-a-handler-on-a-dead-thread

Fix is to wrap the Toast calls in a Runnable in GeofenceTransitionsIntentService:
              mMainThreadHandler.post(new Runnable() {
                @Override
                public void run() {
                  Toast.makeText(GeofenceTransitionsIntentService.this,
                      getString(R.string.entering_geofence),
                          Toast.LENGTH_SHORT).show();
                }

**Comment by thagikura** [comment]
Thanks for your report.
We are looking into the fix.

I'll update the issue once we have a fix.

**Comment by thagikura** [comment]
Internal reference: 19358654

**Comment by thagikura** [comment]
Should be fixed by ed28d7a9da591ea4aec405127370f1c77e893763.
Closing.
