### ISSUE TITLE
Error Launching

### ISSUE THREAD

**Issue by nutpoasa1** [googlesamples/android-Geofencing#10]
When trying to launch this application the log shows 3 errors mainly complaining of no MainActivity in the wearable module.
Here is the Event Log:
Error while executing: am start -n "com.example.android.wearable.geofencing/com.example.android.wearable.geofencing.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.example.android.wearable.geofencing/.MainActivity }
Error type 3
Error: Activity class {com.example.android.wearable.geofencing/com.example.android.wearable.geofencing.MainActivity} does not exist.

Error while Launching activity

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
