### ISSUE TITLE
Geofences not working in Android Oreo with JobIntentService and the IntentService as well.

### ISSUE THREAD

**Issue by pramodit** [googlesamples/android-Geofencing#11]
Geofences doesnt seeem to be working with me in Android O . Can you please assist me over on how do i maintain the service to keep running for the transition / triggers to occur.

**Comment by febimfelix** [comment]
It would be great if someone can answer this issue. It is causing huge issues in Oreo and above devices and making our apps not usable.

**Comment by rameshsambu-dev** [comment]
Even in low-end devices below oreo, it's working fine.When I'm using oreo devices it is not working in background but its working in foreground

**Comment by varun7952** [comment]
https://developer.android.com/about/versions/oreo/background-location-limits.html

**Comment by varun7952** [comment]
check limitation of background services from Android O
https://developer.android.com/about/versions/oreo/background-location-limits.html

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
