### ISSUE TITLE
Geofences triggered only once

### ISSUE THREAD

**Issue by shehabic** [googlesamples/android-Geofencing#2]
When I create a list of Geodences as on your example only the 1st event enter or exit is triggered until I reinitialize thE location client again, I used your exact sample code I don't have this issue with the older version of Google Play Services.

Is there something I need to tell the client after serving the 1st event on a geofence to continue listening?

**Comment by keyboardsurfer** [comment]
Internal: 26816072

**Comment by JoseAlcerreca** [comment]
Hey shehabic, 

How are you experiencing this? Mock or real locations?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
