### ISSUE TITLE
Client disconnected from Google Play Services

### ISSUE THREAD

**Issue by ghita1newrosoft** [googlesamples/android-Geofencing#4]
I got this error
"Failed to send data item: com.google.android.gms.wearable.PutDataMapRequest@3fe7e5e5"

In GeofenceTransitionsIntentService class

**Comment by jwburnside** [comment]
Same error on a Nexus 6 (5.1.1). Code came from sample repo on Android Studio 1.4.

**Comment by codingjeremy** [comment]
This sample has been deprecated.

Have a look at the DataLayer example, as that covers sending Data between phone and wear.
