### ISSUE TITLE
Please explain Google

### ISSUE THREAD

**Issue by powder366** [googlesamples/android-Geofencing#8]
https://github.com/chenjishi/android_location_demo/issues/2

**Comment by keyboardsurfer** [comment]
The issues on our sample repositories should only be used for issues with the samples. In order to get an answer on your own code, we recommend using [stackoverflow](stackoverflow.com).

**Comment by powder366** [comment]
Your samples does not work. When register the Intent with:

private PendingIntent getGeofenceTransitionPendingIntent() {
  | Intent intent = new Intent(this, GeofenceTransitionsIntentService.class);
  | return PendingIntent.getService(this, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
  | }

It triggers but after a while it stops. Why? (I do not reboot my mobile)

**Comment by TheRealAWebb** [comment]
I had the same issue I found two solutions that worked.  One was turning Battery optimization off for my app.  And the other was using a foregroundservice pendingintent for oreo devices.
//Option 2 code example
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
  pendingIntent = PendingIntent.getForegroundService(context, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
}else{
 pendingIntent = PendingIntent.getService(mContext, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
}

Just remember to call  startForeground() in the  handing Intent

**Comment by codeslubber** [comment]
What a mess this whole thing is. Documentation was not updated to O, it's still using an IntentService, this sample is deprecated, and it uses a BroadcastReceiver but I still see people saying call the service directly. Horror show... seriously this is the work of one of the 3 or 4 most powerful companies on the planet? Gonna laugh next time I see the android devs scolding their flock for not testing enough.
