### ISSUE TITLE
Pending intent is removed

### ISSUE THREAD

**Issue by powder366** [googlesamples/android-Geofencing#9]
Your samples does not work. When register the Intent with:

private PendingIntent getGeofenceTransitionPendingIntent() {
  | Intent intent = new Intent(this, GeofenceTransitionsIntentService.class);
  | return PendingIntent.getService(this, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
  | }

It triggers but after a while it stops. Why? (I do not reboot my mobile)

Also see:
https://github.com/googlesamples/android-Geofencing/issues/8

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
